openapi: 3.0.0
servers:
  - description: Copier-Coller API
    url: 'http://localhost:8080/copier-coller-api'
info:
  version: 1.0.0
  title: Copier-Coller API
  description: ''
paths:
  /discovery:
    get:
      summary: Get all registered schemas
      description: Returns all registered schemas
      operationId: get-all-schemas
      responses:
        '200':
          description: Schemas found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSchema'
        '404':
          description: Not found
    post:
      summary: Post new json schema
      description: Post new json schema
      operationId: add-new-schema
      responses:
        '201':
          description: New Json schema successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSchema'
        '409':
          description: Already exists
    put:
      summary: Update existing json schema
      description: Update existing json schema
      operationId: update-schema
      responses:
        '200':
          description: Json schema successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSchema'
  '/discovery/{schemaId}':
    get:
      summary: Get specific schema
      description: Get specific schema
      parameters:
        - schema:
            type: string
          name: schemaId
          in: path
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSchema'
        '409':
          description: Already exists
  /cache:
    put:
      summary: Put Datas in cache
      description: Put datas in cache
      responses:
        '200':
          description: Json schema successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datas'
    get:
      summary: Get Datas from cache
      description: Get datas from cache
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datas'
        '404':
          description: Not found
    parameters: []
components:
  schemas:
    Datas:
      description: Datas wrapper
      type: object
      properties:
        key:
          type: string
        schemaId:
          type: string
        bag:
          type: object
      required:
        - schemaId
        - bag
    DataSchema:
      description: datas bag json-schema
      type: object
      properties:
        schemaId:
          type: string
        schema:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
