/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CaApiControllerApi
 */
@Ignore
public class CaApiControllerApiTest {

    private final CaApiControllerApi api = new CaApiControllerApi();

    /**
     * Liste des Autorités de Certification de confiance utilisées par la plateforme.
     *
     * Opération qui permet au client de prendre connaissance des Autorités de Certification de confiance utilisées par la plateforme. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCATest() {
        List<String> response = api.getCA();

        // TODO: test validations
    }
}
