/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.api;

import fr.ans.esignsante.model.Conf;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigurationsApiControllerApi
 */
@Ignore
public class ConfigurationsApiControllerApiTest {

    private final ConfigurationsApiControllerApi api = new ConfigurationsApiControllerApi();

    /**
     * Liste des configurations disponibles.
     *
     * Opération qui permet au client de récupérer les configurations disponibles afin qu&#x27;il puisse utiliser la configuration qui correspond à l&#x27;usage souhaité.   &lt;br&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConfigurationsTest() {
        Conf response = api.getConfigurations();

        // TODO: test validations
    }
}
