/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.api;

import fr.ans.esignsante.model.ESignSanteSignatureReportWithProof;
import fr.ans.esignsante.model.OpenidToken;
import fr.ans.esignsante.model.SignFSEWithProof;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FseApi
 */
@Ignore
public class FseApiTest {

    private final FseApi api = new FseApi();

    /**
     * Signature du hash d&#x27;une feuille de soin électronique avec preuve.
     *
     * L&#x27;opération permet au client de signer le hash d&#x27;un document (non transmis), par exemple le hash d&#x27;une feuille de soin électronique, en pkcs7 détaché ainsi que de générer une preuve de vérification de signature.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signatureFSEWithProofTest() {
        String secret = null;
        Long idSignConf = null;
        String hash = null;
        String idFacturationPS = null;
        String typeFlux = null;
        List<String> signers = null;
        Long idVerifSignConf = null;
        String requestId = null;
        String proofTag = null;
        String applicantId = null;
        List<OpenidToken> xOpenidToken = null;
        ESignSanteSignatureReportWithProof response = api.signatureFSEWithProof(secret, idSignConf, hash, idFacturationPS, typeFlux, signers, idVerifSignConf, requestId, proofTag, applicantId, xOpenidToken);

        // TODO: test validations
    }
}
