/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.api;

import fr.ans.esignsante.model.ESignSanteSignatureReport;
import fr.ans.esignsante.model.ESignSanteSignatureReportWithProof;
import java.io.File;
import fr.ans.esignsante.model.OpenidToken;
import fr.ans.esignsante.model.SignFSEWithProof;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SignaturesApiControllerApi
 */
@Ignore
public class SignaturesApiControllerApiTest {

    private final SignaturesApiControllerApi api = new SignaturesApiControllerApi();

    /**
     * Signature du hash d&#x27;une feuille de soin électronique avec preuve.
     *
     * L&#x27;opération permet au client de signer le hash d&#x27;un document (non transmis), par exemple le hash d&#x27;une feuille de soin électronique, en pkcs7 détaché ainsi que de générer une preuve de vérification de signature.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signatureFSEWithProofTest() {
        String secret = null;
        Long idSignConf = null;
        String hash = null;
        String idFacturationPS = null;
        String typeFlux = null;
        List<String> signers = null;
        Long idVerifSignConf = null;
        String requestId = null;
        String proofTag = null;
        String applicantId = null;
        List<OpenidToken> xOpenidToken = null;
        ESignSanteSignatureReportWithProof response = api.signatureFSEWithProof(secret, idSignConf, hash, idFacturationPS, typeFlux, signers, idVerifSignConf, requestId, proofTag, applicantId, xOpenidToken);

        // TODO: test validations
    }
    /**
     * Signature d&#x27;un document au format Pades Baseline B.
     *
     * L&#x27;opération permet au client de signer un document PDF au format PADES Baseline B. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signaturePadesTest() {
        String secret = null;
        Long idSignConf = null;
        File file = null;
        List<String> signers = null;
        ESignSanteSignatureReport response = api.signaturePades(secret, idSignConf, file, signers);

        // TODO: test validations
    }
    /**
     * Signature d&#x27;un document PDF au format Pades Baseline B avec preuve.
     *
     * L&#x27;opération permet au client de signer un document au format PADES Baseline B ainsi que de générer une preuve de vérification de signature.&lt;br&gt; Le client peut demander la vérification des règles applicables suivantes:&lt;br&gt;  &amp;nbsp;&amp;nbsp;&amp;nbsp;validité de la signature du certificat;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;présence de la balise \&quot;SigningTime\&quot; dans la signature;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp; présence du certificat utilisé dans la signature; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le certificat de signature n&#x27;est pas expiré; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;l&#x27;usage de la clé du certificat correspond à un usage de signature électronique et de non répudiation;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le certificat de signature n&#x27;est pas révoqué; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;présence d&#x27;une signature qui n&#x27;est pas vide; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;l&#x27;Autorité de Certification est reconnue;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le contenu de la signature est valide;&lt;br&gt;&lt;br&gt;  Le client peut également demander l&#x27;extraction des métadonnées suivantes: &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le DN du certificat;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;la date de signature;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le rapport du diagnostique;&lt;br&gt; &amp;nbsp;&amp;nbsp;&amp;nbsp;le document original non signé.&lt;br&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signaturePadesWithProofTest() {
        String secret = null;
        Long idSignConf = null;
        File file = null;
        List<String> signers = null;
        Long idVerifSignConf = null;
        String requestId = null;
        String proofTag = null;
        String applicantId = null;
        List<OpenidToken> xOpenidToken = null;
        ESignSanteSignatureReportWithProof response = api.signaturePadesWithProof(secret, idSignConf, file, signers, idVerifSignConf, requestId, proofTag, applicantId, xOpenidToken);

        // TODO: test validations
    }
    /**
     * Signature d&#x27;un document au format XMLdsig
     *
     * L&#x27;opération permet au client de signer un document au format XMLDsig-core-1. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signatureXMLdsigTest() {
        String secret = null;
        Long idSignConf = null;
        File file = null;
        ESignSanteSignatureReport response = api.signatureXMLdsig(secret, idSignConf, file);

        // TODO: test validations
    }
    /**
     * Signature d&#x27;un document au format XMLdsig avec preuve
     *
     * L&#x27;opération permet au client de signer un document au format XMLDsig-core-1 ainsi que de générer une preuve de vérification de signature. &lt;br&gt;Le client peut demander la vérification des règles applicables suivantes:&lt;br&gt; &amp;nbsp;&amp;nbsp;&amp;nbsp;validité de la signature du certificat;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;présence de la balise \&quot;SigningTime\&quot; dans la signature;&lt;br&gt;    &amp;nbsp;&amp;nbsp;&amp;nbsp;présence du certificat utilisé dans la signature; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le certificat de signature n&#x27;est pas expiré; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;l&#x27;usage de la clé du certificat correspond à un usage de signature électronique et de non répudiation;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le certificat de signature n&#x27;est pas révoqué; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;présence d&#x27;une signature qui n&#x27;est pas vide; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;l&#x27;Autorité de Certification est reconnue;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le contenu de la signature est valide;&lt;br&gt;&lt;br&gt;  Le client peut également demander l&#x27;extraction des métadonnées suivantes: &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le DN du certificat;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;la date de signature;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le rapport du diagnostique;&lt;br&gt;   &amp;nbsp;&amp;nbsp;&amp;nbsp;le document original non signé.&lt;br&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signatureXMLdsigWithProofTest() {
        String secret = null;
        Long idSignConf = null;
        File file = null;
        Long idVerifSignConf = null;
        String requestId = null;
        String proofTag = null;
        String applicantId = null;
        ESignSanteSignatureReportWithProof response = api.signatureXMLdsigWithProof(secret, idSignConf, file, idVerifSignConf, requestId, proofTag, applicantId);

        // TODO: test validations
    }
    /**
     * Signature d&#x27;un document au format Xades Baseline B.
     *
     * L&#x27;opération permet au client de signer un document au format XADES Baseline B. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signatureXadesTest() {
        String secret = null;
        Long idSignConf = null;
        File file = null;
        List<String> signers = null;
        ESignSanteSignatureReport response = api.signatureXades(secret, idSignConf, file, signers);

        // TODO: test validations
    }
    /**
     * Signature d&#x27;un document au format Xades Baseline B avec preuve.
     *
     * L&#x27;opération permet au client de signer un document au format XADES Baseline B ainsi que de générer une preuve de vérification de signature.&lt;br&gt; Le client peut demander la vérification des règles applicables suivantes:&lt;br&gt;  &amp;nbsp;&amp;nbsp;&amp;nbsp;validité de la signature du certificat;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;présence de la balise \&quot;SigningTime\&quot; dans la signature;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp; présence du certificat utilisé dans la signature; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le certificat de signature n&#x27;est pas expiré; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;l&#x27;usage de la clé du certificat correspond à un usage de signature électronique et de non répudiation;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le certificat de signature n&#x27;est pas révoqué; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;présence d&#x27;une signature qui n&#x27;est pas vide; &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;l&#x27;Autorité de Certification est reconnue;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le contenu de la signature est valide;&lt;br&gt;&lt;br&gt;  Le client peut également demander l&#x27;extraction des métadonnées suivantes: &lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le DN du certificat;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;la date de signature;&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;le rapport du diagnostique;&lt;br&gt; &amp;nbsp;&amp;nbsp;&amp;nbsp;le document original non signé.&lt;br&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signatureXadesWithProofTest() {
        String secret = null;
        Long idSignConf = null;
        File file = null;
        List<String> signers = null;
        Long idVerifSignConf = null;
        String requestId = null;
        String proofTag = null;
        String applicantId = null;
        List<OpenidToken> xOpenidToken = null;
        ESignSanteSignatureReportWithProof response = api.signatureXadesWithProof(secret, idSignConf, file, signers, idVerifSignConf, requestId, proofTag, applicantId, xOpenidToken);

        // TODO: test validations
    }
}
