/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.ans.esignsante.model.Rule;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * ConfVerifSign
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-04T13:37:15.229Z[GMT]")
public class ConfVerifSign implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("idVerifSignConf")
  private Long idVerifSignConf = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("rules")
  private List<Rule> rules = new ArrayList<Rule>();

  @JsonProperty("metaData")
  private List<String> metaData = new ArrayList<String>();

  public ConfVerifSign idVerifSignConf(Long idVerifSignConf) {
    this.idVerifSignConf = idVerifSignConf;
    return this;
  }

   /**
   * Identifiant de configuration. Cet identifiant est utilisé par le service de vérification de signature.
   * @return idVerifSignConf
  **/
  @Schema(required = true, description = "Identifiant de configuration. Cet identifiant est utilisé par le service de vérification de signature.")
  public Long getIdVerifSignConf() {
    return idVerifSignConf;
  }

  public void setIdVerifSignConf(Long idVerifSignConf) {
    this.idVerifSignConf = idVerifSignConf;
  }

  public ConfVerifSign description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description de la configuration de vérification de signature.
   * @return description
  **/
  @Schema(required = true, description = "Description de la configuration de vérification de signature.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ConfVerifSign rules(List<Rule> rules) {
    this.rules = rules;
    return this;
  }

  public ConfVerifSign addRulesItem(Rule rulesItem) {
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Liste des règles qui seront utilisées pour vérifier la signature.
   * @return rules
  **/
  @Schema(required = true, description = "Liste des règles qui seront utilisées pour vérifier la signature.")
  public List<Rule> getRules() {
    return rules;
  }

  public void setRules(List<Rule> rules) {
    this.rules = rules;
  }

  public ConfVerifSign metaData(List<String> metaData) {
    this.metaData = metaData;
    return this;
  }

  public ConfVerifSign addMetaDataItem(String metaDataItem) {
    this.metaData.add(metaDataItem);
    return this;
  }

   /**
   * Données complémentaires et paramétrables retournées par le service.
   * @return metaData
  **/
  @Schema(required = true, description = "Données complémentaires et paramétrables retournées par le service.")
  public List<String> getMetaData() {
    return metaData;
  }

  public void setMetaData(List<String> metaData) {
    this.metaData = metaData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfVerifSign confVerifSign = (ConfVerifSign) o;
    return Objects.equals(this.idVerifSignConf, confVerifSign.idVerifSignConf) &&
        Objects.equals(this.description, confVerifSign.description) &&
        Objects.equals(this.rules, confVerifSign.rules) &&
        Objects.equals(this.metaData, confVerifSign.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idVerifSignConf, description, rules, metaData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfVerifSign {\n");
    
    sb.append("    idVerifSignConf: ").append(toIndentedString(idVerifSignConf)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
