/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.ans.esignsante.model.Erreur;
import fr.ans.esignsante.model.Metadata;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * ESignSanteValidationReport
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-04T13:37:15.229Z[GMT]")
public class ESignSanteValidationReport implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("erreurs")
  private List<Erreur> erreurs = new ArrayList<Erreur>();

  @JsonProperty("metaData")
  private List<Metadata> metaData = new ArrayList<Metadata>();

  @JsonProperty("valide")
  private Boolean valide = null;

  public ESignSanteValidationReport erreurs(List<Erreur> erreurs) {
    this.erreurs = erreurs;
    return this;
  }

  public ESignSanteValidationReport addErreursItem(Erreur erreursItem) {
    this.erreurs.add(erreursItem);
    return this;
  }

   /**
   * Get erreurs
   * @return erreurs
  **/
  @Schema(required = true, description = "")
  public List<Erreur> getErreurs() {
    return erreurs;
  }

  public void setErreurs(List<Erreur> erreurs) {
    this.erreurs = erreurs;
  }

  public ESignSanteValidationReport metaData(List<Metadata> metaData) {
    this.metaData = metaData;
    return this;
  }

  public ESignSanteValidationReport addMetaDataItem(Metadata metaDataItem) {
    this.metaData.add(metaDataItem);
    return this;
  }

   /**
   * Get metaData
   * @return metaData
  **/
  @Schema(required = true, description = "")
  public List<Metadata> getMetaData() {
    return metaData;
  }

  public void setMetaData(List<Metadata> metaData) {
    this.metaData = metaData;
  }

  public ESignSanteValidationReport valide(Boolean valide) {
    this.valide = valide;
    return this;
  }

   /**
   * Get valide
   * @return valide
  **/
  @Schema(required = true, description = "")
  public Boolean isValide() {
    return valide;
  }

  public void setValide(Boolean valide) {
    this.valide = valide;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ESignSanteValidationReport esignSanteValidationReport = (ESignSanteValidationReport) o;
    return Objects.equals(this.erreurs, esignSanteValidationReport.erreurs) &&
        Objects.equals(this.metaData, esignSanteValidationReport.metaData) &&
        Objects.equals(this.valide, esignSanteValidationReport.valide);
  }

  @Override
  public int hashCode() {
    return Objects.hash(erreurs, metaData, valide);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ESignSanteValidationReport {\n");
    
    sb.append("    erreurs: ").append(toIndentedString(erreurs)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    valide: ").append(toIndentedString(valide)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
