/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
/**
 * HashedSecret
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-04T13:37:15.229Z[GMT]")
public class HashedSecret implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("secureSecretHash")
  private String secureSecretHash = null;

  public HashedSecret secureSecretHash(String secureSecretHash) {
    this.secureSecretHash = secureSecretHash;
    return this;
  }

   /**
   * Le Hash du secret.
   * @return secureSecretHash
  **/
  @Schema(required = true, description = "Le Hash du secret.")
  public String getSecureSecretHash() {
    return secureSecretHash;
  }

  public void setSecureSecretHash(String secureSecretHash) {
    this.secureSecretHash = secureSecretHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HashedSecret hashedSecret = (HashedSecret) o;
    return Objects.equals(this.secureSecretHash, hashedSecret.secureSecretHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secureSecretHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HashedSecret {\n");
    
    sb.append("    secureSecretHash: ").append(toIndentedString(secureSecretHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
