/*
 * eSignSante
 * API du composant eSignSante. <br>Ce composant dit de \"signature\" mutualise et homogénéise la mise en oeuvre des besoins autour de la signature. <br>Il permet de signer des documents ainsi que de vérifier la validité d'une signature ou d'un certificat.    <br>
 *
 * OpenAPI spec version: 2.5.0.11
 * Contact: esignsante@asipsante.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.esignsante.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * SignDocument
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-04T13:37:15.229Z[GMT]")
public class SignDocument implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("secret")
  private String secret = null;

  @JsonProperty("idSignConf")
  private Long idSignConf = null;

  @JsonProperty("file")
  private File file = null;

  @JsonProperty("signers")
  private List<String> signers = null;

  public SignDocument secret(String secret) {
    this.secret = secret;
    return this;
  }

   /**
   * Secret
   * @return secret
  **/
  @Schema(description = "Secret")
  public String getSecret() {
    return secret;
  }

  public void setSecret(String secret) {
    this.secret = secret;
  }

  public SignDocument idSignConf(Long idSignConf) {
    this.idSignConf = idSignConf;
    return this;
  }

   /**
   * Identifiant de configuration à sélectionner parmi la liste des configurations disponibles pour la signature (appel de l&#x27;opération \&quot;/configurations\&quot;).
   * @return idSignConf
  **/
  @Schema(required = true, description = "Identifiant de configuration à sélectionner parmi la liste des configurations disponibles pour la signature (appel de l'opération \"/configurations\").")
  public Long getIdSignConf() {
    return idSignConf;
  }

  public void setIdSignConf(Long idSignConf) {
    this.idSignConf = idSignConf;
  }

  public SignDocument file(File file) {
    this.file = file;
    return this;
  }

   /**
   * Document à signer.
   * @return file
  **/
  @Schema(required = true, description = "Document à signer.")
  public File getFile() {
    return file;
  }

  public void setFile(File file) {
    this.file = file;
  }

  public SignDocument signers(List<String> signers) {
    this.signers = signers;
    return this;
  }

  public SignDocument addSignersItem(String signersItem) {
    if (this.signers == null) {
      this.signers = new ArrayList<String>();
    }
    this.signers.add(signersItem);
    return this;
  }

   /**
   * Liste des signataires délégataires. L&#x27;IHM swagger ne gère qu&#x27;1 seul signer - pour gérer plusieurs signers, rajouter des paramètres à la requête CURL.&lt;br&gt;Exemple: curl -X POST [...] -F \&quot;signers&#x3D;Dupont\&quot; -F \&quot;signers&#x3D;Dupond\&quot;
   * @return signers
  **/
  @Schema(example = "[\"curl -X POST [...] -F \\\"signers=Dupont\\\" -F \\\"signers=Dupond\\\"\",\" \"]", description = "Liste des signataires délégataires. L'IHM swagger ne gère qu'1 seul signer - pour gérer plusieurs signers, rajouter des paramètres à la requête CURL.<br>Exemple: curl -X POST [...] -F \"signers=Dupont\" -F \"signers=Dupond\"")
  public List<String> getSigners() {
    return signers;
  }

  public void setSigners(List<String> signers) {
    this.signers = signers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignDocument signDocument = (SignDocument) o;
    return Objects.equals(this.secret, signDocument.secret) &&
        Objects.equals(this.idSignConf, signDocument.idSignConf) &&
        Objects.equals(this.file, signDocument.file) &&
        Objects.equals(this.signers, signDocument.signers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secret, idSignConf, Objects.hashCode(file), signers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignDocument {\n");
    
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    idSignConf: ").append(toIndentedString(idSignConf)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    signers: ").append(toIndentedString(signers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
